#' add_format_to_data
#' 
#' @description Add format to data.
#'
#' @param df_to_format A data generated by the read_sas function.
#' @param df_format A format file generated by the read_format function.
#'
#' @return The df_to_format files with the added format.
#' @export
#'
#' @examples
#' \dontrun{
#' path_data_file <- "data.sas7bdat"
#' df_to_format <- read_sas(format_file = path_data_file)
#' path_format_file <- "formats.sas7bdat"
#' df_format <- read_format(format_file = path_format_file)
#' 
#' res <- add_format_to_data(df_to_format = df_to_format,
#' df_format = df_format)
#' }
#' 
add_format_to_data <- function(df_to_format,
                               df_format){
  vecColnames_to_format <- colnames(df_to_format)[colnames(df_to_format) %in% df_format$Variable]
  
  # column <- vecColnames_to_format[1]
  for(column in vecColnames_to_format){
    attr <- attr(df_to_format[, column], 'label')
    
    dfThesaurusLight <- df_format %>%
      dplyr::filter(.data$Variable == column)
    
    df_to_format <- df_to_format %>%
      dplyr::mutate_at(.vars = column,
                       .funs = function(x) factor(x,
                                                  levels = dfThesaurusLight$Modality,
                                                  labels = dfThesaurusLight$Label))
    attr(df_to_format[, column], 'label') <- attr
    attr(df_to_format[, column], 'var_label') <- attr
  }
  
  return(df_to_format)
}
